# Generated by Django 2.2.6 on 2020-10-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumna',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('identificacion', models.CharField(choices=[('RE', 'Registro Civil'), ('TI', 'Targeta Identidad'), ('CE', 'Cedula')], max_length=12)),
                ('sexo', models.CharField(choices=[('F', 'Femenino')], max_length=10)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('grado', models.CharField(choices=[('TR', 'Transicion'), ('PR', 'Primero'), ('SE', 'Segundo'), ('TE', 'Tercero'), ('CUA', 'Cuarto A'), ('CUB', 'Cuarto B'), ('QUA', 'Quinto A'), ('QUB', 'Quinto B'), ('SEA', 'Sexto A'), ('SEB', 'Sexto B'), ('SPA', 'Septimo A'), ('SPB', 'Septimo B'), ('OCA', 'Octavo A'), ('OCB', 'Octavo B'), ('NOA', 'Noveno A'), ('NOB', 'Noveno B'), ('NOC', 'Noveno C'), ('DEA', 'Decimo A'), ('DEB', 'Decimo B'), ('DEC', 'Decimo C'), ('ONA', 'Once A'), ('ONB', 'Once B'), ('ONC', 'Oce C')], max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('eps', models.CharField(max_length=20)),
                ('arl', models.CharField(max_length=20)),
                ('grupo_rh', models.CharField(choices=[('RO', 'O+'), ('RA', 'A+'), ('RA2', 'A-'), ('RB', 'B+'), ('RB2', 'B-'), ('RAB', 'AB+'), ('RAB2', 'AB-'), ('RO2', 'O-')], max_length=10)),
                ('hobby', models.CharField(max_length=20)),
            ],
        ),
    ]
