# Generated by Django 2.2.6 on 2020-10-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0001_initial'),
        ('alumna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='antecedentes_medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='alumna',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acudiente.persona'),
        ),
        migrations.AddField(
            model_name='alumna',
            name='antecedentes_medicos',
            field=models.ManyToManyField(to='alumna.antecedentes_medicos'),
        ),
    ]
