# Generated by Django 2.2.6 on 2020-10-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumna', '0002_auto_20201024_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumna',
            name='tipo_identificacion',
            field=models.CharField(choices=[('RE', 'Registro Civil'), ('TI', 'Targeta Identidad'), ('CE', 'Cedula')], default=10, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumna',
            name='identificacion',
            field=models.IntegerField(null=True),
        ),
    ]
