# Generated by Django 2.2.6 on 2020-10-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumna', '0003_auto_20201024_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumna',
            name='modalidad_matricula',
            field=models.CharField(choices=[('I', 'Interna'), ('E', 'Externa')], default='Externa', max_length=15),
            preserve_default=False,
        ),
    ]
