# Generated by Django 3.1.2 on 2020-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumna', '0004_alumna_modalidad_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumna',
            name='tipo_identificacion',
            field=models.CharField(choices=[('RE', 'Registro Civil'), ('TI', 'Tarjeta Identidad'), ('CE', 'Cedula')], max_length=12),
        ),
    ]
