# Generated by Django 3.1.2 on 2020-11-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumna', '0005_auto_20201107_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='antecedentes_medicos',
            new_name='antecedentes_medico',
        ),
        migrations.RenameField(
            model_name='alumna',
            old_name='antecedentes_medicos',
            new_name='antecedentes_medico',
        ),
    ]
