# Generated by Django 3.1.2 on 2020-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumna', '0007_auto_20201109_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumna',
            name='hobby',
            field=models.CharField(choices=[('BA', 'Bailar'), ('CA', 'Cantar'), ('FU', 'Futbol'), ('BO', 'Boleybol'), ('BAS', 'Baloncesto'), ('AJ', 'Ajedrez'), ('CI', 'Cine'), ('MU', 'Musica'), ('PA', 'Patinar'), ('VI', 'Viajar'), ('LE', 'Leer'), ('DI', 'Dibujar'), ('OT', 'Otro')], max_length=20),
        ),
    ]
